apiVersion: v1
data:
  nginx.conf: |
    events { }
    http {
      server {
        listen 80;
        location /hodr/ {
          proxy_pass http://hodr.fampay-dev.svc.cluster.local:8080/;
          proxy_set_header Host $host;
        }
        location /bran/ {
          proxy_pass http://bran.fampay-dev.svc.cluster.local:8000/;
          proxy_set_header Host $host;
        }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fampay-dev