apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: fampay-dev
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-proxy
  sessionAffinity: None
  type: NodePort
